project:
  type: website

website:
  title: "Cecilia Zumajo-Cardona"
  navbar:
    left:
      - href: about.qmd
        # text: Home
      - research.qmd
      - publications.qmd
      - scicomm.qmd
    tools:
      - icon: twitter
        href: https://twitter.com/CeciZumajo
      - icon: github 
        href: https://github.com/cezumajo
        
format:
  html:
    theme: cyborg
    css: styles.css
    toc: true

editor: visual


