project:
  type: website

website:
  title: "Cecilia Zumajo-Cardona"
  site-url: cezumajo.github.io
  repo-url: https://github.com/cezumajo/cezumajo.github.io
  favicon: favicon.png
  navbar:
    right:
      - href: about.qmd
        # text: Home
      - "research/index.qmd"
      - "publications/index.qmd"
      - "scicomm/scicomm.qmd"
      
    tools:
      - icon: github 
        href: https://github.com/cezumajo
        
  page-footer: 
    left: Cecilia Zumajo-Cardona © 2024 is licensed under [CC BY 4.0](https://creativecommons.org/licenses/by/4.0/)
    right: cezumajo@gmail.com {{< fa envelope >}} Made with {{< fa brands r-project >}} and [![](https://quarto.org/quarto.png){fig-alt="Quarto" width=65px}](https://quarto.org/)

        
format:
  html:
    theme: cyborg
    css: styles.css
    toc: true

editor: visual


