---
title: "Deciphering the evolution of the ovule genetic network through expression analyses in <i>Gnetum gnemon</i>"
author:
  - name: "**Cecilia Zumajo-Cardona**"
    orcid: 0000-0002-9516-6112
  - name: Barbara Ann Ambrose
year: 2021
date: 2021-05
publication: Annals of Botany 
doi: 10.1093/aob/mcab059
materials: ""

categories:
  - AINTEGUMENTA
  - BELL1
  - Gnetum
  - integument
  - KANADI
  - seed evolution
  - neosynangial hypothesis
  - UNICORN
---

## Abstract

• **Background and aims** The ovule is a synapomorphy of all seed plants (gymnosperms and angiosperms); however, there are some striking differences in ovules among the major seed plant lineages, such as the number of integuments or the orientation of the ovule. The genetics involved in ovule development have been well studied in the model species *Arabidopsis thaliana*, which has two integuments and anatropous orientation. This study is approached from what is known in arabidopsis, focusing on the expression patterns of homologues of four genes known to be key for the proper development of the integuments in arabidopsis: *AINTEGUMENTA (ANT), BELL1, (BEL1), KANADIs (KANs)* and *UNICORN (UCN)*.

• **Methods** We used histology to describe the morphoanatomical development from ovules to seeds in *Gnetum gnemon*. We carried out spatiotemporal expression analyses in *G. gnemon*, a gymnosperm, which has a unique ovule morphology with an integument covering the nucellus, two additional envelopes where the outermost becomes fleshy as the seed matures, and an orthotropous orientation.

• **Key Results** Our anatomical and developmental descriptions provide a framework for expression analyses in the ovule of *G. gnemon*. Our expression results show that although *ANT, KAN* and *UCN* homologues are expressed in the inner integument, their spatiotemporal patterns differ from those found in angiosperms. Furthermore, all homologues studied here are expressed in the nucellus, revealing major differences in seed plants. Finally, no expression of the studied homologues was detected in the outer envelopes.

• **Conclusions** Altogether, these analyses provide significant comparative data that allows us to better understand the functional evolution of these gene lineages, providing a compelling framework for evolutionary and develop- mental studies of seeds. Our findings suggest that these genes were most likely recruited from the sporangium development network and became restricted to the integuments of angiosperm ovules.


## Citation

>Zumajo-Cardona, C., &amp; Ambrose, B. A. (2021). Deciphering the evolution of the ovule genetic network through expression analyses in <i>Gnetum gnemon</i>. <i>Annals of Botany</i>, <i>128</i>(2), 217-230. https://doi.org/10.1093/aob/mcab059
